### ISSUE TITLE
map not found

### ISSUE THREAD

**Issue by petacube** [google/clif#14]
i am in examples folder. clif compiled and run ok. however
i run 
make callbacks
In file included from /dev/stdin:1:
/opt/clif/python/types.h:28:10: fatal error: 'map' file not found
#include <map>
         ^~~~~
_BackendError: Matcher failed with status 1
make[3]: *** [callbacks/python/CMakeFiles/callbacks] Error 4
make[2]: *** [callbacks/python/CMakeFiles/callbacks.dir/all] Error 2
make[1]: *** [callbacks/python/CMakeFiles/callbacks.dir/rule] Error 2
make: *** [callbacks] Error 2

I have added this to CMakeLists:
-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1

it now shows a different error:make callbacks
No suitable matches found for Set (with C++ name: clif_example::callbacks::Set) on line 21.
    Function parameter types didn't match.
    Rejected Candidate:
      clif_example::callbacks::Set at /opt/clif/../clif/examples/callbacks/callbacks.h:41:1
    Parameter 2. 
 Compare:
    Clif Type: "clif_example::callbacks::Data" with 
     C++ Type: "::std::shared_ptr< ::clif_example::callbacks::Data>"
    Do all output parameters follow all input parameters?
_BackendError: Matcher failed with status 1
make[3]: *** [callbacks/python/CMakeFiles/callbacks] Error 4
make[2]: *** [callbacks/python/CMakeFiles/callbacks.dir/all] Error 2
make[1]: *** [callbacks/python/CMakeFiles/callbacks.dir/rule] Error 2
make: *** [callbacks] Error 2

**Comment by mrovner** [comment]
We don't support OS X yet, sorry.

**Comment by gpshead** [comment]
We _believe_ that it tends to be missing C++11 enabling compiler flags when this happens. I did get things to build and run upon first release on MacOS but we are seeing issues like this crop up when trying to build the examples so I must not have done that part.  We'll need some MacOS continuous integration in the future.

**Comment by yilei** [comment]
clang defaults to libc++ on macOS, so if you also checkout the libcxx project before building llvm, it should work. i.e. change https://github.com/google/clif/blob/6c6d894a112d978bd5abfcab1052c60c5ee365a9/INSTALL.sh#L99 to:

```
cd llvm/projects
svn co https://llvm.org/svn/llvm-project/libcxx/trunk@307315 libcxx
cd ../tools
```

This should be fixed in the next clif release.

**Comment by laike9m** [comment]
@yilei Sadly, this still doesn't work and will give the same error('map' file not found).

**Comment by rwgk** [comment]
This repo was unmaintained from December 2017 to September 2019.                
It was recently updated, see https://github.com/google/clif/discussions/36#discussioncomment-85120 for some background.
                                                                                
If this issue is still relevant please repopen it or ask questions at https://github.com/google/clif/discussions/.
